#!/usr/bin/env bash
# Displays "Best School" 10 times and says Hi at the 9th iteration 

text="Best School"
i=0

while ((i++ < 10)); do
    echo "$text"
    if [ "$i" -eq 9 ]; then
        echo "Hi"
    fi
done
