#!/usr/bin/env bash
# This script is displaying "Best School" 10 times with the while loop

text="Best School"
i=0

while ((i++ < 10)); do
    echo "$text"
    if [ "$i" -eq 9 ]; then
        echo "Hi"
    fi
done
