#!/usr/bin/env bash
# Lopps between 1 and 10 and does a certain task at specific loops

i=0
text="Best School"

while ((i++ <= 10)); do
    if [ "$i" -eq 4 ]; then
        echo "bad luck"
    elif [ "$i" -eq 9 ]; then
        echo "good luck"
    else
        echo "$text"
    fi
done
