#!/usr/bin/env bash
# Counts 1 to 20 and does a task at specific loops

i=0

while ((i++ < 20)); do
    echo "$i"
    if [ "$i" -eq 4 ]; then
        echo "bad luck from China"
    fi
    if [ "$i" -eq 9 ]; then
        echo "bad luck from Japan"
    fi
    if [ "$i" -eq 17 ]; then
        echo "bad luck from Italy"
    fi
done
