#!/usr/bin/env bash
# Displays time notation

hour=-1

while ((hour++ <= 12)); do
    if [ "$hour" -eq 13 ]; then
        break
    fi

    echo "Hour: $hour"
    min=0

    while ((++min < 60)); do
        echo "$min"
    done

done
