#!/usr/bin/env bash
# Displays time notation

hour=0

while ((hour++ <= 12)); do
    echo "Hour: $hour"
    if [ "$hour" -eq 12 ]; then
        break
    fi

    min=0
    while ((++min < 60)); do
        echo "$min"
    done

done
