#!/usr/bin/env bash
# Displays time notation

for ((hour = 0; hour <= 12; hour++)); do
    echo "Hour: $hour"
    if [ "$hour" -eq 12 ]; then
        break
    fi
    for ((min = 1; min < 60; min++)); do
        echo "$min"
    done
done
